// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.

class Solution {
    public char findTheDifference(String s, String t) {
        if (s.length() == 0)
            return t.charAt(0);
        
        char ans = s.charAt(0);
        for (int i = 1; i < s.length(); i++) {
            ans = (char)(ans ^ s.charAt(i));
        }
        for (int i = 0; i < t.length(); i++) {
            ans = (char)(ans ^ t.charAt(i));
        }
        return ans;
    }
}
